# Generated by Django 4.2.4 on 2023-08-18 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_employee_position_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Управление', 'verbose_name_plural': 'Управления'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Сектор', 'verbose_name_plural': 'Сектора'},
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='patronymic',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('military', 'Военнослужащий'), ('civil', 'Госслужащий')], default='military', max_length=8),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='base.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='management',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='base.management'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='base.sector'),
        ),
    ]
