# Generated by Django 4.2.4 on 2023-08-19 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_employee_is_manager_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='is_manager_department',
            new_name='is_manager_office',
        ),
    ]
